name: Fortnite Status API Auto Update

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  api-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Update status API
        run: node index.js

      - name: Commit API updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add public/status.json public/status-badge.json public/history.json || true
          git diff --cached --quiet && exit 0

          git commit -m "Auto update Fortnite status API"
          git push
